### PR TITLE
Fix parameter name

### PR DESCRIPTION
**Pull request by keefertaylor**
## High Level Overview of Change

The server returns `addressDetailType` not `addressDetailsType`.

### Context of Change

This feels backwards to me because the other field is called `addressDetails`.

### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

## Before / After

Compliant to server

## Test Plan

CI

### CODE REVIEW

**Comment by keefertaylor** [comment]
Without a definitive guide, I'm going to merge this and adopt the change across Xpring SDK.

**Comment by hbergren** [comment]
I think it might make more sense to update the PayID server to return `addressDetailsType`.

I know that's a breaking change, but we probably have one coming up anyways with Dino's return all addresses feature, and I want to make _another_ breaking change to the private API, to switch the `pay_id` property to `payId` to be consistent with the public API.

**Comment by keefertaylor** [comment]
Can we file an Asana issue to track this @hbergren / @dino-rodriguez ?  I'm happy to leave this as is AS LONG as we're tracking why it's not compatible with the server version.

**Comment by hbergren** [comment]
https://app.asana.com/0/1143722888069470/1175597112527169

(This is a subtask of that. I just grouped all the potential Breaking Changes things I can think of).

**Comment by keefertaylor** [comment]
TY Hans!

**Pull request closed without merging**
