### PR TITLE
Updates .gitignore to ignore auto-generated files in VSCode

### PR DESCRIPTION
**Pull request by amiecorso**
## High Level Overview of Change
Something is automatically producing (and re-generating) the following files in VSCode:
```
scripts/.settings/*
scripts/.classpath
scripts/.project
```
and this update prevents them from getting pushed to master.

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

## Before / After
.gitignore up to date for anyone with the same files present.

## Test Plan
CI

### CODE REVIEW

**Comment by amiecorso** [comment]
Noah I put you on here because these files actually seem like an eclipse/Java thing and maybe you know why they appeared in this project (which I'm looking at in VSCode).  If not, no worries.

**Comment by tedkalaw** [comment]
have you found any docs on these files? any hints on docs that might suggest what conditions cause them to be generated?

**Comment by nkramer44** [comment]
.project and .classpath look like eclipse files to me, but maybe VS code uses the same files types?

Whatever their purpose, they definitely shouldn't be in the git repo

**Comment by tedkalaw** [comment]
still curious if we have any leads on why this is happening...is this vscode? the only reason i ask is that it seems odd to grow `.gitignore` with files unique to a person's env - you could imagine this file being arbitrarily long

**Pull request merged**
